fix bugs

diff --git a/bashdb b/bashdb
--- a/bashdb
+++ b/bashdb
@@ -1,23 +1,24 @@
 #!/bin/bash
+#set -o xtrace
 _dbname=${0##*/} #equal to basename
 
 if (($#<1)) ; then
-	echo "$_dbname: Usage: $_dbnam filename" >&2
-	exit 1
+   echo "$_dbname: Usage: $_dbnam filename" >&2
+   exit 1
 fi
 
-_guineapig=$1
+_gunieapig="$PWD/$1"
 
 if [ ! -r $1 ]; then
-	echo "$_dbname: Cannot read file '$_guineapig'." >&2
-	exit 1
+   echo "$_dbname: Cannot read file '$_guineapig'." >&2
+   exit 1
 fi
 
 shift
 
 _tmpdir=/tmp
-_libdir=.
+_libdir=${PWD}
 _debugfile=$_tmpdir/bashdb.$$
 
 cat $_libdir/bashdb.pre $_gunieapig > $_debugfile
-exec bash $_debugfile $_guineapig $_tmpdir $_libdir "$@"
+exec bash $_debugfile $_gunieapig $_tmpdir $_libdir "$@"
