library

diff --git a/wicked/inpath b/wicked/inpath
--- a/wicked/inpath
+++ b/wicked/inpath
@@ -14,7 +14,7 @@ in_path()
 	return $retval
 }
 
-check_for_cmd_in_path()
+checkForCmdInPath()
 {
 	var=$1
 
@@ -29,15 +29,15 @@ check_for_cmd_in_path()
 	fi
 }
 
-if [ $# -ne 1 ] ; then
-	echo "Usage: $0 command" >&2 ; exit 1
-fi
-
-check_for_cmd_in_path "$1"
-case $? in
-	0 ) echo "$1 found in PATH" ;;
-	1 ) echo "$1 not found or not executable" ;;
-	2 ) echo "$1 not found in PATH" ;;
-esac
-
-exit 0
+# if [ $# -ne 1 ] ; then
+# 	echo "Usage: $0 command" >&2 ; exit 1
+# fi
+# 
+# checkForCmdInPath "$1"
+# case $? in
+# 	0 ) echo "$1 found in PATH" ;;
+# 	1 ) echo "$1 not found or not executable" ;;
+# 	2 ) echo "$1 not found in PATH" ;;
+# esac
+# 
+# exit 0
